config/routes.rb
Rails.application.routes.draw do
  # get 'books', to: "books#index"
  # get 'books/order'
  # get 'orders/index', to: "orders#index"
  devise_for :users
  root to: 'pages#home'
  resources :books do
    resources :orders, only: [:new,:create,:index] do
      resources :payments, only: [:new,:create,:show]
     # get 'payments/new', to: "payments#new" # --> create a new payment
    # get 'orders/new', to: "orders#new"  #---> this is the page with the part the sell and the personal details!
    # post 'orders/new', to: "orders#create"  #--> This is "ordering" a new book!
    end
  end

  # get 'books/new', to: "books#new"  # --> This is the form to "selling" a new book!
  # post 'books/new', to: "books#create" #--> This is the actually sale (the button, show the book to sell)!
  # get 'books/:id/edit', to: "books#edit" #--> This is edit the book that is for sale!
  # patch 'books/:id/edit', to: "books#update" # --> this is when you press the button and update!
  # delete 'books/:id/destroy', to: "books#destroy" # --> this is deleting the sale page!
  # get 'messages/new', to: "messages#new" # --> Create e a new message
  # post 'messages/new', to: "messages#create" # --> post a new message
  # get 'payments/new', to: "payments#new" # --> create a new payment
  # post 'payments/new', to: "payments#create" #-->post/send the payment
  get 'dashboard', to: "pages#dashboard"
  get 'orders/new', to: "orders#new"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :users
  has_many :messages
  has_one_attached :photo

  validates :author, presence: true
  validates :title, presence: true
  validates :genre, presence: true
  validates :price, presence: true
  validates :description, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_title_and_author_and_genre_and_description,
    against: [ :title, :author, :genre, :description ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :book
  belongs_to :user
  has_one_attached :photo
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :first_name, presence: true
  # validates :photo, presence: true
  # validates :email, presence: true, uniqueness: true
  # validates :encrypted_password, presence: true
  has_one_attached :photo

  has_many :books, dependent: :destroy
  has_many :orders, through: :books
  has_many :messages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      redirect_to books_path(@book)
    end
  end

  def show
    @book = Book.find(params[:id])
    @order = Order.new
  end

  def index
    @order = Order.new
    if params[:query].present?
      @books = Book.search_by_title_and_author_and_genre_and_description(params[:query])
    else
      @books = Book.all
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :price, :description, :photo)
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @order = Order.new
    @order.book = @book
    @order.user = current_user
    @order.status = "Pending seller validation"
    # if @order.confirm
    # @order.value = @order.book.to_f * shipping
    # else
    # @book.value = 0
    # end
    if @order.save
      redirect_to order_path(@order)
      # else ?
    end
  end

  def index
    @orders = Order.where(user_id: current_user.id)
  end

  def show
    @order = Order.find(params[:id])
    @book = @order.book
  end

  def update
    @order = Order.find(params[:id])
    @order.status = "pending seller validation"
    @order.save!
    redirect_to order_path(@order)
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to root_path
  end

  private

  def order_params
    params.require(:order).permit(:book)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @order = Order.new
    @order.book = @book
    @order.user = current_user
    if @order.save
      redirect_to dashboard_path, notice: 'Order Successful!'
    end
  end

  def index
    @orders = Order.where(user_id: current_user.id)
  end

  def show
    @order = Order.find(params[:id])
    @book = @order.book
  end

  def update
    @order = Order.find(params[:id])
    @order.save!
    redirect_to order_path(@order)
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to root_path
  end

  private

  def order_params
    params.require(:order).permit(:book, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end
  def dashboard
    @user = current_user
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @payment = Payment.new
  end

  def create
    @payment = Payments.new(payment_params)
    @payment.user = current_user
  end

  private

  def message_params
    params.require(:payment).permit(:name, :card_number, :date, :cvc, :user_id, :book_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :genre %>
    <%= f.text_field :genre, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <%= f.file_field :photo, direct_upload: true, accept: "image/png,image/gif,image/jpeg" %>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/books/edit.html.erb
<p>this path is get 'books/id/edit', to: "books#edit"</p>

app/views/books/index.html.erb
<div class="row">
  <% @books.each do |book| %>
  <div class="col">
    <div class="card" style="width: 18rem;">
      <%= cl_image_tag book.photo.key, class: "card-img-top" %>
      <div class="card-body">
        <h5 class="card-title"><%= book.title %></h5>
        <p class="card-text"><%= book.author %></p>
        <p class="card-text"><%= book.genre %></p>
        <p class="card-text"><%= book.price %> $</p>
        <%= link_to "See More", book_path(book), class: "btn btn-primary"  %>
      </div>
    </div>
  </div>
  <% end %>
</div>

<hr>

app/views/books/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <hr>
      <h1>Add a Book</h1>
      <hr>
      <%= render 'form', book: @book %>
      <hr>
      <%= link_to books_path do %>
        <i class="fa fa-history"></i> Back to list
      <% end %>
    </div>
  </div>
</div>

app/views/books/order.html.erb
<h1>Book#order</h1>
<p>Find me in app/views/book/order.html.erb</p>

app/views/books/show.html.erb
<div class="row">
  <div class="container">
  <div class="leftcolumn">
    <div class="card">
     <h2>Title: <%= @book.title%></h2>
     <h5>Author: <%= @book.author%></h5>
     <%= cl_image_tag @book.photo.key, class: "card-img-top" %>
     <br>
     <h5>Price: <%= @book.price%>$</h5>
     <br>
     <h6>Genre: <%= @book.genre%></h6>
     <br>
     <h6>Description: <%= @book.description%></h6>
     <br>
    </div>
  </div>
  <div class="rightcolumn">
    <div class="card">
      <h2>The seller</h2>
      <div class="fakeimg" style="height:150px">
        <img src="https://lewagon.masscom.media/assets/images/profile.jpg" alt="customer image" width="150" height="150">
      </div>
      <br>
      <p><%=@book.seller%></p>
    </div>


    <div class="card">
      <h3>Do you like it?</h3>

      <%= simple_form_for [@book,@order] do |f|%>
      <%= f.submit "Buy", class: "btn btn-primary btn-block" %>
      <% end %>

      <br>
    </div>
    <div class="card">
      <h3>Any doubts?</h3>
      <button type="button" class="btn btn-primary">Say Hi</button>
    </div>
  </div>
  </div>
</div>

app/views/books/user.html.erb
<h1>Book#user</h1>
<p>Find me in app/views/book/user.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Le BookStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css"> -->
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>

    <!-- <script src="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script> -->
  </body>
</html>

app/views/orders/index.html.erb
<div class="text-center padded">
  <h2>All my books</h2>
</div>

app/views/orders/new.html.erb
<%= f.label "Book Photo" %>
<%= f.file_field :photo%><br>

app/views/pages/dashboard.html.erb
<div class="container-fluid">
  <div class="row">
    <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <!--2nd portion>-->
      <div class="position-sticky pt-md-5">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
              <span class="ml-2">Home</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
              <span class="ml-2">New books</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
              <span class="ml-2">History</span>
            </a>
          </li>
        </ul>
      </div>
      <!--2nd ends here -->
    </nav>
    <main class="col-md-9 ml-sm-auto col-lg-10 px-md-4 py-4">
      <h1 class="h2">Profile Page</h1>
      <div class="row my-4">
        <div class="col-12">
          <div class="card">
            <h5 class="card-header"><%= @user.first_name %> <%= @user.last_name %></h5>
            <div class="card-body">
              <h5 class="card-title">Details:</h5>
              <p class="card-text">E-mail address: <%= @user.email %></p>
              <p class="card-text text-success">*****</p>
            </div>
          </div>
        </div>

      </div>

      <div class="row">
        <div class="col-12 col-xl-12 mb-4 mb-lg-0">
          <div class="card">
            <h5 class="card-header">Latest transactions</h5>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">Order</th>
                      <th scope="col">Author</th>
                      <th scope="col">Customer</th>
                      <th scope="col">Price</th>
                      <th scope="col">Date</th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="row">17371705</th>
                      <td></td>
                      <td></td>
                      <td>€61.11</td>
                      <td>Aug 31 2020</td>
                      <td><a href="#" class="btn btn-sm btn-primary">View</a></td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <a href="#" class="btn btn-block btn-light">View all</a>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-12 col-xl-12 mb-4 mb-lg-0">
          <div class="card">
            <h5 class="card-header">Bought books</h5>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">Order</th>
                      <th scope="col">Author</th>
                      <th scope="col">Customer</th>
                      <th scope="col">Price</th>
                      <th scope="col">Date</th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="row">17371705</th>
                      <td>Volt Premium Bootstrap 5 Dashboard</td>
                      <td>johndoe@gmail.com</td>
                      <td>€61.11</td>
                      <td>Aug 31 2020</td>
                      <td><a href="#" class="btn btn-sm btn-primary">View</a></td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <a href="#" class="btn btn-block btn-light">View all</a>
            </div>
          </div>
        </div>
      </div>

      <footer class="pt-5 d-flex justify-content-between">
        <ul class="nav m-0">
          <li class="nav-item">
            <a class="nav-link text-secondary" aria-current="page" href="#">Privacy Policy</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-secondary" href="#">Terms and conditions</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-secondary" href="#">Contact</a>
          </li>
        </ul>
      </footer>
    </main>
  </div>
</div>

app/views/pages/home.html.erb
<main role="main">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="first-slide" src="https://images.unsplash.com/photo-1472745433479-4556f22e32c2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="First slide">
        <div class="container">
          <div class="carousel-caption text-left">
            <h1>Discover your next read, ethically.</h1>
            <p>Used books are cheaper and more environmentally friendly vs buying new. LeBookStore brings people passionate about books together to buy and sell direcrtly.</p>
            <p><a class="btn btn-primary sign-up-btn" href="../users/sign_up" role="button">Sign up today</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img class="second-slide" src="https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" alt="Second slide">
        <div class="container">
          <div class="carousel-caption">
            <h1>Browse, buy & sell.</h1>
            <p>With thousands of books listed at any one time, you can always find something great to read. Got books you don't want? List them and earn money</p>
            <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse Books</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img class="third-slide" src="https://images.unsplash.com/photo-1449247666642-264389f5f5b1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="Third slide">
        <div class="container">
          <div class="carousel-caption text-right">
            <h1>Order with a click.</h1>
            <p>Sign up, add your address, and get books delivered to your door.</p>
            <a href="../users/sign_up" class="btn btn-primary sign-up-btn">Sign up</a>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <!-- Marketing messaging and featurettes
      ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->
  <div class="container marketing">
    <!-- Three columns of text below the carousel -->
      <!-- START THE FEATURETTES -->
      <hr class="featurette-divider">
      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">An amazing used book selection. <span class="text-muted"></span></h2>
          <p class="lead">Unlike our trillion dollar competitors, we care about books AND the environment. We think books should be reloved again and again...and our users think so too. Browse our selection!</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-fluid mx-auto" src="https://images.unsplash.com/photo-1512820790803-83ca734da794?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60" alt="Generic placeholder image">
          <hr>
          <button type="button" class="btn btn-block btn-1 btn-1c"><%= link_to "Browse books", books_path %></button>
        </div>
      </div>
      <hr class="featurette-divider">
      <div class="row featurette">
        <div class="col-md-7 order-md-2">
          <h2 class="featurette-heading">Sell with 0% commission. <span class="text-muted"></span></h2>
          <p class="lead">We don't think that charnging our users 30% commission to sell books is cool, we will leave that policy to our trillion dollar competitors and we will focus on helping relove books.</p>
        </div>
        <div class="col-md-5 order-md-1">
          <img class="featurette-image img-fluid mx-auto" src="https://images.unsplash.com/photo-1561715276-a2d087060f1d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60" alt="Generic placeholder image">
          <hr>
          <button type="button" class="btn btn-dark btn-block btn-1c"><%= link_to "Sell a book", new_book_path %></button>
        </div>
      </div>
      <hr class="featurette-divider">
      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">B-corp. <span class="text-muted"></span></h2>
          <p class="lead">To help enure the book industry continues to live-on we donate 10% of our profits to small independent publishers.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-fluid mx-auto" src="https://images.unsplash.com/photo-1579621970795-87facc2f976d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60" alt="Generic placeholder image">
          <hr>
          <button type="button" class="btn btn-dark btn-block"><%= link_to "Learn more", books_path %></button>
        </div>
      </div>
      <hr class="featurette-divider">
      <!-- /END THE FEATURETTES -->
    </div>
    <!-- /.container -->
  </div>
</main>

app/views/payments/_form.html.erb
<%= form_for(@order) do |f| %>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :card_number %>
    <%= f.text_field :card_number, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :name_card %>
    <%= f.number_field :name_card, class: 'form-control' %>
  </div>


  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/payments/new.html.erb
<h1>Purchase!</h1>

<%= render 'form', book: @payment %>

<hr>
<%= link_to books_path do %>
  <i class="fa fa-history"></i> Back to Book
<% end %>

app/views/shared/_footer.html.erb
<footer class="container-fluid bg-grey pt-5 d-flex justify-content-center">
  <div class="">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-8">
            <div class="logo-part">
              <h2><a href="/" class="navbar-brand"><h2><b>Le</b>Book<b>Store</b></h2></a></h2>
              <hr>
              <p>Rua do Conde de Redondo 91B, 1150-103 Lisboa</p>
              <p>Millions of Products, Low € Prices. Free Delivery on Eligible Orders.</p>
            </div>
          </div>
          <div class="col-md-4">
            <h2> About Us</h2>
            <hr>
            <p>But horizontal lines can only be a full pixel high.</p>
            <a href="#" class="btn-footer"> More Info </a><br>
            <a href="#" class="btn-footer"> Contact Us</a>
          </div>
        </div>
      </div>
    </div>
    <hr><br>
  <!-- Footer Text -->
  <p class="float-right"><a href="#">Back to top</a></p>
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">
    <span class="text-center">Copyright &copy; 2019-2020 &middot; <a href="/">LeBookStore, Inc. &middot;</a></span>
  </div>
  <!-- Copyright -->    
  </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
  <a href="/" class="navbar-brand"><b>Le</b>Book<b>Store</b></a>
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- Collection of nav links, forms, and other content for toggling -->
  <div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
    <div class="navbar-nav">
      <a href="/" class="nav-item nav-link">Home</a>
      <a href="#" class="nav-item nav-link">About</a>
      <a href="#" class="nav-item nav-link">Contact</a>
    </div>
<!--     <form class="navbar-form form-inline">
      <div class="input-group search-box">
	  	<div class="input-group">
          <input type="text" id="search" class="form-control" placeholder="Search here...">
		  <div class="input-group-append">
    		<button class="btn btn-primary search-btn" type="button">Search</button>
  		  </div> -->
    <div class="form-inline">
    <!-- <form class="navbar-form form-inline"> -->
    <%= form_tag books_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search by title or author"
      %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
    </div>

		</div>
    </form>
    <div class="navbar-nav ml-auto action-buttons">
      <div class="nav-item dropdown">
        <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle mr-4"><i class="fa fa-key"></i></a>
        <div class="dropdown-menu action-form">
          <p class="hint-text">What would you like to do?</p>
          <div class="form-group social-btn clearfix">
            <% if user_signed_in? %>
              <button type="button" class="btn btn-alert float-left"><%= link_to "Log out", destroy_user_session_path, method: :delete %></button>
            <% else %>
              <a href="<%= new_user_session_path %>" class="btn btn-primary float-left"><i class="fa fa-key"></i> Login</a>
            <% end %>
            <a href="../users/password/new" class="btn btn-primary float-right">Reset</a>
          </div>
          <div class="or-seperator"><b>or</b></div>
          <div>
            <p class="hint-text">Would you rather browse the store?</p>
            <button type="button" class="btn btn-dark btn-block"><%= link_to "Browse Books", books_path %></button>
          </div>
        </div>
      </div>
      <div class="nav-item dropdown">
        <a href="../users/sign_up" class="btn btn-primary sign-up-btn">Sign up</a>
      </div>
    </div>
  </div>
</nav>